### ISSUE TITLE
rename Option type to Maybe

### ISSUE THREAD

**Issue by tylerkahn** [puffnfresh/roy#102]
[Prelude line 70](https://github.com/pufuwozu/roy/blob/master/lib/prelude.roy#L70) defines an Option type which is (best I can tell) semantically equivalent to Haskell's Maybe type (the eliminator function is even called maybe). This is pretty minor but I think it would provide more clarity and familiarity to have the type constructor named Maybe and the data constructors  be named Just and Nothing.

**Comment by espringe** [comment]
+1 I think the current naming is taken from Scala, but Roy's 'Option' is far closer to Haskell's Maybe or C++'s Optional, than it is to Scala's Option. (Scala's Option[T] is a 4-state beast (not 2 like haskell), that is only really useful when T is or can be a primitive

**Comment by kputnam** [comment]
@espringe I don't think that's accurate. Scala's Option type has only two constructors: Some and None. Perhaps you're thinking of Lift's "Box", which has three constructors? Secondly, Scala doesn't distinguish primitive types from reference types like Java does (http://www.scala-lang.org/node/128).

**Comment by espringe** [comment]
Yes it does, it's just more subtle about it.  Also, you're forgetting about the Null/Nothing subclass.  If T is a reference type, for instance imagine a function that accepts an Option[String], there are four distinct states the type system will allow it be given: null, None, Some(null), Some(String).

Hence why I've found that Option[T] is only really useful and performant if T is or could be a primitive (e.g. Option[Int] ).

But if you ever did something like this in Scala: `case class LinkedList[T](payload: T, rest: Option[LinkedList[T]]))` you would be misusing Option. (As you can simply leave it out, to get a faster, more predictable and has-less-stupid-state version. On the other hand, this is the exact sort of definition you'd want in Roy/Haskell

**Comment by kputnam** [comment]
I understand your point, but it seems analogous to saying Maybe has four states because Haskell's type system allows `undefined` and `Just undefined` as values of `Maybe Int`. It's not apples-to-apples, but I think the differences are attributable to language semantics rather than Option vs Maybe.

Anyway I don't have a horse in this race; either name would be fine with me. Just wanted to clarify what you meant by Option having four states. Sorry about the digression!

**Comment by puffnfresh** [comment]
It's actually taken from OCaml.

http://ocaml-lib.sourceforge.net/doc/Option.html
