### ISSUE TITLE
--print and --eval/--stdio option like coffeescript

### ISSUE THREAD

**Issue by gregwebs** [puffnfresh/roy#109]
I want to integrate Roy with the Haskell Yesod web framework. Currently I have coffeescript integrated. It is ran with `coffee -epb`. --eval takes a string instead of a file. --print dumps the output to stdout.

**Comment by gregwebs** [comment]
I am switching from -epb to -spb. from eval to stdin. So if Roy can take stdin and put the results on stdout that would be great!

**Comment by puffnfresh** [comment]
I just quickly added this.

The flag is called `--stdio`. Thanks!

**Comment by gregwebs** [comment]
tested it out, works well, thanks!

**Comment by joneshf** [comment]
This was not actually added to the list of help options.  I added that and browser here: https://github.com/pufuwozu/roy/pull/167
