### ISSUE TITLE
use contracts.coffee parser

### ISSUE THREAD

**Issue by gregwebs** [puffnfresh/roy#119]
I have ran into a lot of issues with the roughness of the parser. In addition, coffeescript has a lot of features (multi-line strings, string interpolation, ...) that Roy could get for free.

I think Roy would be on a lot better footing if it started with the coffeescript compiler and worked its way backwards. I would be fine with using coffeescript syntax actually. I would only protest if Roy switched from layout-based to brackets or used the full 'function' keyword. Roy isn't about copying Haskell syntax, it is about types!

Adopting coffeescript syntax would provide a lot of benefits. I am already writing in coffeescript, so transitioning my code to Roy would be a minimal amount of work. If I decided to abandon Roy, that would also require less work. Supporting abandoning is important for uptake. I was able to use coffeescript because I was able to claim that if we don't like it, we can just use the generated javascript.

I am trying out contracts.coffee now: http://disnetdev.com/contracts.coffee/

This project uses coffeescript syntax but also adds type annotations (they aren't actually types though, they are turned into contracts). It is being kept up to date, and seems like a perfect base for Roy.

**Comment by natecain** [comment]
+1

**Comment by LeifW** [comment]
CoffeeScript syntax lacks support for do-notation I believe, but there's that "mofor" branch someone submitted.

**Comment by rtfeldman** [comment]
At this late hour it seems safe to say Roy will not be using the CoffeeScript compiler as a base.
