### ISSUE TITLE
make fallback to JavaScript global explicit

### ISSUE THREAD

**Issue by dckc** [puffnfresh/roy#140]
In types.rst, I see:

> Referring to unknown identifier will assume that the identifier refers to a native JavaScript global.

?!

Is that really on purpose? introduction.rst says implicit globals are dangerous, no?

> JavaScript has the var keyword to create local variables but unqualified assignments write to the global object:

How about an analog to the `/* global */` directive from [JSLint](http://www.jslint.com/lint.html)?

> JSLint also recognizes a /_global_/ directive that can indicate to JSLint that variables used in this file were defined in other files."

**Comment by sophiebits** [comment]
Seconding this. This in conjunction with #17 would make JS globals much nicer.

**Comment by dckc** [comment]
My interest in this issue is overtaken by the emergence of purescript.
