### ISSUE TITLE
Clean installation on OSX fails

### ISSUE THREAD

**Issue by non** [puffnfresh/roy#144]
So, I just installed Node.js and then cloned roy, and ran make deps.

I end up hitting:

```
npm http 404 https://registry.npmjs.org/interleave/0.1.1
npm ERR! Error: version not found: 0.1.1 : interleave/0.1.1

...

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/erik/w/roy
npm ERR! node -v v0.8.4
npm ERR! npm -v 1.1.45
```

Is this known? Expected? Should I be doing something different?

I only installed Node.js to use Roy, so it's likely I'm doing something dumb.

**Comment by puffnfresh** [comment]
Looks like interleave 0.1.1 has been removed from the repository. I know the author - asking him why.

I'll update to a newer version and see if it works soon.

**Comment by puffnfresh** [comment]
Looks like 0.5.11 is fine.

**Comment by non** [comment]
Yeah I can confirm that the fix works. Thanks!
