### ISSUE TITLE
Allow optional semicolons

### ISSUE THREAD

**Issue by DanBurton** [puffnfresh/roy#147]
The motivation for this is using the repl. Suppose I want to write this function (contrived example):

```
let foo x =
  let bar y = x + y
  bar
```

I'm unaware of how to enter multi-line statements into the repl, so it would be nice to do this:

```
let foo x = let bar y = x + y; bar
```

**Comment by rtfeldman** [comment]
Is this something we definitely do or do not want? I have no preference, except that we should close the issue if it's not going to make it in.

**Comment by joneshf** [comment]
Personally, I would prefer to not have semi-colons.  As far as the repl itself, can't we use the node repl to support  multilines?

Also, agreed about the issues.  There's a good deal sticking around that should be trimmed.

**Comment by joneshf** [comment]
If there's still want for semi-colons feel free to open this up again, however, the example you posted should parse now.

``` roy
roy> let foo x =
....   let bar y = x + y
....   bar
.... 
roy> foo
function (x) {
    var bar = function (y) {
        return x + y;
    };
    return bar;
} : Function(Number, Function(Number, Number))
roy> foo 3
function (y) {
        return x + y;
    } : Function(Number, Number)
roy> (foo 3) 4
7 : Number
```
