### ISSUE TITLE
Vim plugin seems to break things

### ISSUE THREAD

**Issue by disolovyov** [puffnfresh/roy#150]
I'm not a great Vim scripter, but I have a hunch the `plugin/roy.vim` should be `ftplugin/roy.vim` instead.

First of all, `plugin/roy.vim` deals with file-specific settings, so it sounds like a filetype plugin, not a global one.

Second, by making it a global plugin, it seems to break other filetype plugins. Specifically, I have a bad feeling about this line:

``` vim
let b:did_ftplugin = 1
```

Can @jb55 or anyone else correct me on this?

**Comment by jb55** [comment]
You're seem to be correct :)

**Comment by disolovyov** [comment]
I see you have a separate repo for [Vim-Roy](/jb55/Vim-Roy), and you fixed it there. Shouldn't it be linked to misc here?
