### ISSUE TITLE
Use Escodegen

### ISSUE THREAD

**Issue by puffnfresh** [puffnfresh/roy#151]
https://github.com/Constellation/escodegen

Then we can get rid of string concatenation and be sure that we're emitting valid JavaScript.

**Comment by michaelficarra** [comment]
**+1e6**! Also, free source maps.

**Comment by Constellation** [comment]
Wow! If you have question about impl & API of escodegen, feel free to ask us :-)

**Comment by cassiemeharry** [comment]
I just landed a branch that implements this. Free sourcemaps aren't included yet, but should be in soon.
