### ISSUE TITLE
Please publish new roy version to npm

### ISSUE THREAD

**Issue by paulmillr** [puffnfresh/roy#173]
the old one errors

**Comment by ericbmerritt** [comment]
+1

**Comment by joneshf** [comment]
@puffnfresh A good deal has changed since 0.1.5 was released.  How do you feel about going to version 0.2.0 after #178 is fixed?  Also, are we using semver for our versioning?

**Comment by joneshf** [comment]
#180 is about the site, but still related.

**Comment by puffnfresh** [comment]
Busy this week but I'll publish to npm and a new version of the site this weekend.

**Comment by joneshf** [comment]
Coolio!

**Comment by puffnfresh** [comment]
Published! https://npmjs.org/package/roy
