### ISSUE TITLE
Add travis support

### ISSUE THREAD

**Issue by joneshf** [puffnfresh/roy#176]
I think it'd be nice to have travis set up here.  Anyone see a reason not to set this up?

**Comment by puffnfresh** [comment]
A while ago I setup a [drone.io](https://drone.io/) build for Roy - just as a test. Works great!

[![Build Status](https://drone.io/github.com/pufuwozu/roy/status.png)](https://drone.io/github.com/pufuwozu/roy/latest)

If you create an account, I can add you as a collaborator. I can also move to or create a Travis build for Roy if there's a need.

**Comment by joneshf** [comment]
Done, same username as here [joneshf](https://drone.io/joneshf).  Is there an advantage to drone over travis?  Does drone have service hooks to test pull requests?  I remember now that was what I was actually wanting out of travis.

EDIT: I see now it has some interesting features and supports more than just github.  I'll look into adding a hook on github for it.

**Comment by puffnfresh** [comment]
@joneshf support for GitHub's Commit Status API would be very useful. I'll add a Travis build if it's too tricky to get working with Drone.

**Comment by joneshf** [comment]
Thanks for adding me.  Here's what I've found.  We can add a service hook for pull requests to drone on github.  That would send a message to drone.  Drone would interpret it as though a commit was pushed to master and try to build master.  Since they are parsing the JSON we don't have access to what was actually sent.  We could create a custom build script to handle this, and have it curl the github api for this repo to see what's new, then decide what to build.  But it seems like too much work.  At least for me.

Drone is supposed to add support for pull requests in the [future](https://drone.uservoice.com/forums/176976-feedback-for-drone-io/suggestions/3538935-github-s-pull-request-hook).  If you're alright with it, we can use travis in the mean time, and switch back to drone once they get pull requests set up.

Or, if you're feeling cavalier/bored, you can setup a script to check [pull requests](http://developer.github.com/v3/pulls/#list-pull-requests), see if they're [new](http://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-sha) and build them, then [report the status](http://developer.github.com/v3/repos/statuses/#create-a-status).  Unfortunately, I think that master would have to be rebuilt after every pull request just to ensure that the status badge for master doesn't change due to a bunk pull request.

**Comment by joneshf** [comment]
Well, I got bored and started something.  We'll see how it turns out.

**Comment by joneshf** [comment]
Looks like 4-8 weeks.  So nevermind the build script I was working on.  I think this should stay open until there is pull request support, be that travis or drone.

**Comment by puffnfresh** [comment]
Setup a Travis build at: https://travis-ci.org/pufuwozu/roy

**Comment by joneshf** [comment]
So, it looks like travis has stopped building because of the namechange from pufuwozu to puffnfresh.  Can you change the travis build?  Drone is still going strong, they just need to add PR support so we can ditch travis.

**Comment by joneshf** [comment]
Cool, I see you updated it.  Thanks.

Also, I'm going to remove the drone badge from the readme for now.  I don't think we need two badges showing the build passed.
