### ISSUE TITLE
Support for scientific notated numbers?

### ISSUE THREAD

**Issue by LarryBattle** [puffnfresh/roy#180]
Does Roy support scientific notated numbers?

Example:
Roy:

```
console.log 1E32
```

Output JS

```
(function() {
console.log(1, E32);
})();
```

Output:

ReferenceError: E32 is not defined

Used http://roy.brianmckenna.org/

**Comment by joneshf** [comment]
The version that is on the site is a bit outdated.  There was support for lowercase `e` up until now.  I've just added uppercase `E` as well as `+` in the exponent.  Until we get a more current version up on the site, you can clone this repo and have support for scientific notation.

**Comment by puffnfresh** [comment]
Website has been updated, example now works.

**Comment by LarryBattle** [comment]
Thanks for your hard work. It works now. :+1:
