### ISSUE TITLE
Use commonjs-everywhere

### ISSUE THREAD

**Issue by puffnfresh** [puffnfresh/roy#181]
We've been using Rigger to handle bundling but commonjs-everywhere would be a lot easier and probably less fragile.

https://github.com/michaelficarra/commonjs-everywhere

**Comment by michaelficarra** [comment]
I'd be happy to help out with this. Should be really easy. Just point it at the module's entry point.

**Comment by puffnfresh** [comment]
Did it last night with 63817baff5edf4892b68de6659d5ef75821640be
