### ISSUE TITLE
Fix errors from enabling more jshint options

### ISSUE THREAD

**Issue by puffnfresh** [puffnfresh/roy#190]
Just looking at the JSHint options. Chuck the following under `grunt.initConfig`:

``` js
jshint: {
    options: {
        //onevar: true,
        es3: true,
        indent: 4,
        noarg: true,
        node: true,
        trailing: true,
        undef: true,
        unused: true
    }
}
```

At the moment, looks like there's a few potential global leakages. We definitely don't want that.

I'm also proposing we use `onevar` soon. Just to enforce a style.

**Comment by jedws** [comment]
indent 2 surely? :-)

cheers,
jed.
