### ISSUE TITLE
Text editor plugins

### ISSUE THREAD

**Issue by paulmillr** [puffnfresh/roy#2]
It is very hard to write some code without proper syntax highlighting. I could start work on TextMate bundle as it's my everyday editor.

As a temporary solution, we could use color highlighting of some other language. @pufuwozu syntax of which language, in your opinion, is the most similar to **roy**'s?

**Comment by puffnfresh** [comment]
Roy is a bit of a mishmash of language syntaxes. I would probably say that it's most similar to an ML language.

I started writing a highlighter for [CodeMirror 2](http://codemirror.net/) but started hitting some problems. I wanted to have CodeMirror 2 support so that I could make a better "Try Roy" site.

Eventually I'm also going to work on an Emacs mode.

**Comment by abi** [comment]
- 1

**Comment by alvivi** [comment]
I added basic support for TextMate/SublimeText on my roy repository. I'm trying to figure out how to do a pull request attached to this issue (I'm a github newbie).

**Comment by puffnfresh** [comment]
@alvivi not sure how to do it against existing issues :thumbsdown:

I think it's fine to just do a pull request with a new issue, possibly referencing #2

**Comment by paulmillr** [comment]
@alvivi in my opinion, roy textmate bundle / emacs mode should be located in separate repositories. Just as coffeescript addons.

**Comment by puffnfresh** [comment]
@paulmillr I'm happy for them to be in the repository. No harm if they're 100 lines of code.

**Comment by paulmillr** [comment]
@pufuwozu usual bundles are 1000-3000+ LOC -- https://github.com/jashkenas/coffee-script-tmbundle

**Comment by alvivi** [comment]
Seems to be a matter of taste, some [projects](http://code.google.com/p/go/source/browse#hg%2Fmisc) have editor support in the same repository and others have not. 

As you want :)

**Comment by esehara** [comment]
I write Simple Syntax File for Vim. :)

Draft Version is here:
https://github.com/esehara/Vim-Roy

**Comment by paulmillr** [comment]
@alvivi I've created [repo for textmate bundle](https://github.com/paulmillr/roy.tmbundle) and added you as contributor.

**Comment by jordwalke** [comment]
Thanks a ton @esehara / @paulmillr
