### ISSUE TITLE
guide.roylang.org dns is down

### ISSUE THREAD

**Issue by WuTheFWasThat** [puffnfresh/roy#206]
not sure where else to report this

**Comment by schas002** [comment]
:+1:

**Comment by benjaminapetersen** [comment]
Still down.  Assuming it is the best place for a tutorial, tho not sure if 2 months down means the project is suspended?

**Comment by vendethiel** [comment]
The last commit on this repo was in 2013. I think the project has been suspended for some time.

**Comment by michaelficarra** [comment]
I believe @puffnfresh sees [PureScript](http://www.purescript.org/) as a spiritual successor.

**Comment by puffnfresh** [comment]
Yeah, use PureScript - has same goals, hits them better :+1:

**Comment by schas002** [comment]
@puffnfresh so basically, project abandoned? If so, I'd be kinda willing to maintain. :)

**Comment by vendethiel** [comment]
Is there a reason why you don't use PureScript?
