### ISSUE TITLE
Multiple declarations of data constructor allowed in same scope

### ISSUE THREAD

**Issue by jameshfisher** [puffnfresh/roy#25]
Given

```
data Tree = Foo | Foo
```

I get the JS

```
var Foo = function(){};
var Foo = function(){};
```

where equivalent Haskell complains: `ERROR line 1 - Multiple declarations for data constructor "Foo"`

See http://codepad.org/b7yFXkvp

**Comment by puffnfresh** [comment]
Fixed in daad80b24083cb1d4a082eec94eb57c4dbe3d87b
