### ISSUE TITLE
Recursive datatypes not allowed (?)

### ISSUE THREAD

**Issue by jameshfisher** [puffnfresh/roy#26]
Given

```
data List a = Cons a (List a) | Nil
```

or

```
data Tree a = Tree (Tree a) a (Tree a) | Nil
```

etc., I get the (syntactic) error

```
Error: Parse error on line 2: Unexpected 'IDENTIFIER'
```

Not sure what this is referring to; line 2 does not exist.

Haskell accepts these declarations.

**Comment by puffnfresh** [comment]
I've been working on this for the past few days. I know what the problem in Roy's type system is, just need to fix it.

**Comment by puffnfresh** [comment]
This should be fixed in f8465a08756f5393b1c05d6f602cf73dc3acc878 :)

**Comment by jameshfisher** [comment]
Not sure what version is on http://roy.brianmckenna.org/, but tagged unions are now broken.  On the example I get the error

```
Error: Multiple declarations for data constructor: Some
```

**Comment by puffnfresh** [comment]
I wasn't clearing the state on each type-check. Should be fixed now.
