### ISSUE TITLE
Fix Roy Repl to use multi-line or ";".

### ISSUE THREAD

**Issue by esehara** [puffnfresh/roy#29]
Example Python:

```
>>> def test():
...         pass
... 
>>> 
```

ghci (Haskell):

```
Prelude> let test x = do{if x == 1 then 0 else x * 2}
Prelude> test 2
4
```

but, Roy:

```
roy> let gcd a b =
Error: Parse error on line 2: Unexpected 'EOF'

roy> let gcd a b = if b == 0 then
Error: Parse error on line 2: Unexpected 'EOF'

roy> let gcd a b = if b == 0 then a else gcd b (a % b)
Error: Parse error on line 2: Unexpected 'IDENTIFIER'

roy> let gcd a b = ;if b == 0 then;a;else;gcd b (a % b)
Couldn't tokenise: 
```

It should be able to use multi-line or ";".

**Comment by joneshf** [comment]
You should be able to do multi line stuff now.  So the first two examples should open up a new line for you to add most stuff to it.  The third example should just parse the whole thing like nobody's business.  The last example however, still wont tokenize.
