### ISSUE TITLE
Unicode keywords

### ISSUE THREAD

**Issue by paulmillr** [puffnfresh/roy#33]
[Scala](http://cemerick.com/2011/07/14/scala-isnt-complicated-its-clever/) / [Haskell](http://www.haskell.org/haskellwiki/Unicode-symbols) support unicode keywords as an alternative to default ones.

`\` `λ`
`<-` `←`
`->` `→`
`=>` `⇒`

What do you think about this idea?

**Comment by puffnfresh** [comment]
I love this idea. Having Unicode support for built-in syntax would be awesome.

What to do about non-built-in syntax like in #16 might be a later issue.

**Comment by piranha** [comment]
Well, I believe that introducing too many syntax constructs will make language noisy. Also it will introduce wars for coding style and decrease consistency. ;-) I.e. I believe Python philosophy should be followed - 'There should be one-- and preferably only one --obvious way to do it.'

**Comment by paulmillr** [comment]
> Also it will introduce wars for coding style and decrease consistency

Nope, as we may see in haskell's / scala's example.

These are not additional constructs, they're just aliases

**Comment by piranha** [comment]
> These are not additional constructs, they're just aliases

That's what I'm talking about. TIMTOWTDI. Perl, Ruby and to some extent CoffeeScript suffer from it.

**Comment by piranha** [comment]
Also, good editors make it possible to show unicode symbols instead of language constructs in case you want some prettiness.

**Comment by paulmillr** [comment]
> Also, good editors make it possible to show unicode symbols instead of language constructs in case you want some prettiness.

Noone would see this prettiness except me then.

I think that Roy should follow the way of functional programming languages like scala & haskell instead of pythonic imperative one. Personally, I don't think there's should be only one way to do it, but definitely language shouldn't have 5 ways of doing the same thing etc (perl).

Scala also has [nice community-drived coding style guide](http://davetron5000.github.com/scala-style/index.html). And, as I saw, scala code is very consistent.

**Comment by piranha** [comment]
> Noone would see this prettiness except me then.

It's not like this prettiness will make something easier. It's not easier to read, not easier to write, and someone without configured keybindings will send you patches with `->`, inconsistent with your pretty codebase with `→`. This will be a pain point.

> I think that Roy should follow the way of functional programming languages like scala & haskell instead of pythonic imperative one. 

I'm not sure I follow how is consistency bound to functional/imperative styles? Let's say roy should follow the way of functional programming languages like lisp instead of perl imperative one, would this better explain my opinion?

**Comment by michaelficarra** [comment]
related coffeescript discussion: jashkenas/coffee-script#1679

**Comment by puffnfresh** [comment]
Just wanted to say that I completely see both sides here.

It might increase inconsistency but hopefully a good style guide will eventually arise to mitigate that.

**Comment by esehara** [comment]
I vote for "be able not to Unicode operator as default syntax". 

I like this idea,but I do not want Unicode Operator to be contained in default syntax.

Because I think that it becomes a cause by which a code becomes complicated. the core syntax should be kept simple.(and I love The Zen of Python "There should be one way to do it." ;) ).

Instead, I propose enabling it to use Unicode Operator as a standard module. 

example:

```
import UnicodeOperator
```

**Comment by paulmillr** [comment]
It's "complicated" only because programmers don't have a simple way to write those symbols. So this is a problem of tools, not language. And, IMO, this problem can be solved easily. All we need is an emacs mode & vim plugin (textmate bundle with support of symbols exists already).

**Comment by piranha** [comment]
It's complicated because:

1) you've got alternative syntax for language;
2) you won't be able to fix something with your phone or dumb terminal;
3) isn't that enough?

It may be pretty, but it's arguably complicates language. Is Haskell or Scala simple (rhetorical question)?

**Comment by paulmillr** [comment]
> you won't be able to fix something with your phone or dumb terminal;

I am able to fix something because it's an alternative syntax, not only.

**UPD:**
[Scala isn't complicated, it's clever](http://cemerick.com/2011/07/14/scala-isnt-complicated-its-clever).

**Comment by alvivi** [comment]
I'd prefer to follow the rule "only one way to do things...". In Haskell we got unicode symbols, but almost nobody use them (they have more uses in Literate Haskell, for pedagogical uses). If Roy provides unicode symbols the users will have option of use them, but the "entropy" of the language will be a little higher. Seems a matter of taste, and IMHO, not a high priority feature.

**Comment by paulmillr** [comment]
Here's a simple script that replaces all the things :octocat::

`sed -e "s/\\\/λ/g;s/<-/←/g;s/->/→/g;s/=>/⇒/g"`

``` bash
➜ echo 'let a = \\a -> \\b -> \\c -> do return d <- e' \
  | sed -e "s/\\\/λ/g;s/<-/←/g;s/->/→/g;s/=>/⇒/g"
let a = λa → λb → λc → do return d ← e
```

I've implemented it as a command in TextMate / Sublime2 (**⇧⌘P**).

**Comment by esehara** [comment]
The number of character codes is not one. There are Shift-jis,EUC-JP,ISO-2022-JP in Japan.
In fact, if "←" as not Unicode is inputted, an error "Couldn't tokenize" will occur. 

It seems in me that there is no character code agreement in Roy,
because I think it excessive to use a multi-byte's operator(Unicode Operator) as default syntax.
and I want not to recommend only Unicode.

**Comment by paulmillr** [comment]
> There are Shift-jis,EUC-JP,ISO-2022-JP in Japan.

Yep, there's many encodings, but Unicode is only one we need **in our case**, it's 2011 at all. For example, I use TextMate. It doesn't support anything but unicode. What should I do when I see source code in some strange foreign encoding? Node.js doesn't support anything but unicode & ascii. Javascript itself is a unicode thing.

I'm very glad that we are in the "unicode future", where most websites use one universal encoding.

Just to note: Scala's very popular libraries, like Akka & Scalaz use this arrows, see [example](https://github.com/jboner/akka/blob/master/akka-samples/akka-sample-fsm/src/main/scala/DiningHakkersOnBecome.scala#L67).

**Comment by piranha** [comment]
Unicode is not an encoding. UTF-8, UTF-16 and UTF-32 are encodings.
