### ISSUE TITLE
Haskell's "bind" operator

### ISSUE THREAD

**Issue by paulmillr** [puffnfresh/roy#34]
Should we provide `value <- expr` operator as an alternative to `bind val = expr`? Or maybe `value <- expr` should be only valid syntax? Or maybe no `<-` operator at all?

**Comment by puffnfresh** [comment]
Sounds good. I think it's best to stick with existing syntax when possible so I vote for Haskell's (OCaml uses something similar, `<--`).

**Comment by esehara** [comment]
I agree,too.

"<-" is easy to understand "bind" because of graphical. I like it :).
If this issure were adopted, then I am happy.I vote for Haskell's.
