### ISSUE TITLE
Make functions curried

### ISSUE THREAD

**Issue by jameshfisher** [puffnfresh/roy#42]
Given

```
let f a b c = a + b + c

let g = f 1 2
```

I get the error

   Error: Type error: Function(Number,Number,'bnj) is not Function(Number,Number,Number,Number)

from which I gather functions are not curried.  I suggest that they should be; i.e. an unoptimized compilation of the above would give something like

```
var f = function(a) {
  return function(b) {
    return function (c) {
      return a + b + c;
    }
  }
}
var g = f(1)(2);
```

**Comment by jameshfisher** [comment]
We'd require a way of defining uncurried functions in order to state the type of external functions.  Or could these be modelled using tuples?

**Comment by paulmillr** [comment]
This is duplicate of #11.

**Comment by jameshfisher** [comment]
OK.
