### ISSUE TITLE
Another take on the ajax monad example

### ISSUE THREAD

**Issue by kasperlanger** [puffnfresh/roy#58]
To me it makes more sense if "return" returns a jquery promise like this...

```
let deferred = {
  return: \x -> $.when(x)
  bind: \x f -> x.done(f)
}

let v = (do deferred
  value <- $.ajax {url: '/examples/helloworld.roy', payload: 'stuff'}
  console.log value
)
```

This is also more in sync with the monadic laws.

Update:
The above example is broken - I believe this is better:

```
let deferred = {
  return: \x -> $.when(x)
  bind: \x f ->
    let dfd = $.Deferred()
    x.done(\val -> 
        (f val).done(\val2 -> dfd.resolve val2)
    )
    dfd
}

let v = (do deferred
  val <- $.ajax '/examples/helloworld.roy'
  val2 <- $.ajax '/examples/alias.roy'
  return val ++ val2
)

(do deferred
  text <- v
  console.log text
)
```

**Comment by puffnfresh** [comment]
Very awesome!

**Comment by kasperlanger** [comment]
Although the example above works I'm afraid the bind function is broken.
The problem is that the result of the function `f` which is passed to `done` is simply evaluated for side effects and the return value is discarded.

Consider the following example

```
let v = (do deferred
  value <- $.ajax {url: '/examples/helloworld.roy', payload: 'stuff'}
  console.log value
  return "Hay World"
)
```

Here `v` should be a deferred object wrapping `"Hay World"` but is instead the result of the `$.ajax` call.

I think the bind should be something along the following coffeescript (sorry I hit the limit of my roy skills).

``` coffeescript
def_return = x -> $.when(x)
def_bind = (f,x) ->
    dfd = $.Deferred()
    x.done (val) ->
        f(val).done (val2) ->
            dfd.resolve val2
    dfd
```

Here a new deferred object is returned immediately and then when `x` is later resolved it's passed to `f` which again returns a deferred object which is passed a function that finally resolves the deferred object we created in the first place.

The example above should then compile to something like this:

``` coffeescript
v = do ->
    dfd = $.Deferred()
    x = $.ajax {url: '/examples/helloworld.roy', payload: 'stuff'}  
    x.done (val) ->
        console.log val
        $.when("Hay World").done (val2) ->
            dfd.resolve val2
    dfd
```

**Comment by kasperlanger** [comment]
Yay I got it working in roy:

```
let deferred = {
  return: \x -> $.when(x)
  bind: \x f ->
    let dfd = $.Deferred()
    x.done(\val -> 
        (f val).done(\val2 -> dfd.resolve val2)
    )
    dfd
}

let v = (do deferred
  val <- $.ajax '/examples/helloworld.roy'
  val2 <- $.ajax '/examples/alias.roy'
  return val ++ val2
)

(do deferred
  text <- v
  console.log text
)
```

**Comment by piranha** [comment]
This one is just great!
