### ISSUE TITLE
Increase sample code.

### ISSUE THREAD

**Issue by esehara** [puffnfresh/roy#70]
label : Wishlist ?

When writing code, there is a very useful sample code.then I want to increase more sample code.
What we need sample code like?

**Comment by esehara** [comment]
Example [FizzBuzz](http://etfb.dreamwidth.org/76274.html):

```
let isfizzbuzz x = 
  if (x % 15) == 0 then
   console.log("FizzBuzz")
  else
    isbuzz x

let isbuzz x = 
  if (x % 5) == 0 then
   console.log("Buzz")
  else
    isfizz x

let isfizz x =
   if (x % 3) == 0 then
    console.log("Fizz")
   else
    console.log(x)

let fizzbuzz x y = 
   if (x < (y + 1)) then
    isfizzbuzz x
    fizzbuzz (x + 1) y
   else
    console.log("end")

fizzbuzz 1 25
```

**Comment by puffnfresh** [comment]
Thanks!

The FizzBuzz example was added in 17a4d29eac0772242a9c07d97e7b4322d65935db

**Comment by rtfeldman** [comment]
There are now quite a few examples in the repo; any objections to my closing this?

**Comment by puffnfresh** [comment]
@rtfeldman thanks!
