### ISSUE TITLE
"Unexpected 'EOF'" when last line is non-blank

### ISSUE THREAD

**Issue by jameshfisher** [puffnfresh/roy#72]
In some cases (not sure exactly which), not terminating code with a newline causes an `Unexpected 'EOF'` error.  This is for example the case with the following without a newline termination:

``` haskell
let foo = match Bar
  case Bar = true
```

**Comment by puffnfresh** [comment]
Think this was fixed back in 43e78eca0090dc2e2d6aa50dae4401253e073ebb.

Let me know if you find another place that breaks :)
