### ISSUE TITLE
Disallow identically named parameters to same function

### ISSUE THREAD

**Issue by jameshfisher** [puffnfresh/roy#76]
The Roy code

``` haskell
let foo x x = x
```

compiles (0.1.3) to

``` javascript
var foo = function(x, x) {
    return x;
}
```

where it should generate a compiler error like GHC: "Repeated variable "x" in pattern"

**Comment by puffnfresh** [comment]
9f8ab04ee163a5503453a88da1ce5a99dcb24ab8
