### ISSUE TITLE
Disallow identically named type parameters

### ISSUE THREAD

**Issue by jameshfisher** [puffnfresh/roy#77]
The Roy code

``` haskell
data Maybe a a = Nothing | Just a
```

generates (0.1.3) the JS

``` javascript
var Nothing = function(){};
var Just = function(a){this._0 = a};
```

where it should generate a compile error, like GHC: "Repeated type variable "a" on left hand side"

**Comment by puffnfresh** [comment]
30db61531ece2c40e87f3a4e29a1276af85d9c04
