### ISSUE TITLE
Cannot run roy-tests on node (windows)

### ISSUE THREAD

**Issue by sledorze** [puffnfresh/roy#80]
had to add 'node ' before './roy'

child_process.exec 'node ./roy -r ' ++ name (λerror stdout stderr →

I'm new to nodeJs / Js so maybe this is not completely roy related; however tests should be executable whatever the platform IMHO.

**Comment by puffnfresh** [comment]
I committed f1ca20f2f773ba21dec88aef1728791f715a90eb to fix this.

Let me know if it works!

**Comment by joneshf** [comment]
This appears to have been fixed, but there's a few other issues with windows. I'll open a new issue for those in particular.

**Comment by puffnfresh** [comment]
Thanks!
