### ISSUE TITLE
Simple let bindings

### ISSUE THREAD

**Issue by jordwalke** [puffnfresh/roy#89]
Apologies if this has been discussed (it's a hard concept to search for) in the issue tracker.

SML and other functional languages have syntax for creating bindings using the LET ... IN sytax.

Are there plans for doing this in roy? Did I simply miss where this was discussed?

**Comment by rtfeldman** [comment]
As far as I know there are no plans for this. @puffnfresh thoughts?

**Comment by puffnfresh** [comment]
I think it's alright to make people emulate it with an anonymous lambda and immediate application.
