### ISSUE TITLE
How to export functions?

### ISSUE THREAD

**Issue by paulmillr** [puffnfresh/roy#94]
Is there any way to write something like

``` javascript
exports.fn = function() {
  return 1 + 2;
}
```

in roy? It would allow to write modules for node etc.

**Comment by paulmillr** [comment]
oh, I see, #17

**Comment by puffnfresh** [comment]
#17 is for giving types to JS natives. This relates to exporting for CommonJS.

I've been working on modules for the past week. I'm hoping to come up with a way to unify the popular JS module systems and have Roy code work across them all.

You can generate a `.roym` (type information) file from `other_module.roy`:

```
 exports x y
 let x = 100
 let y = 10
```

The generated `other_module.roym`:

```
x: Number
y: Number
```

And you can import it:

```
exports doubleX
import other_module

console.log other_module.x

let doubleX = other_module.x * other_module.x
```

This code should be able to compile to Modules/1.0, AMD and browser globals.

**Comment by puffnfresh** [comment]
Pushed a commit which makes modules work in Roy: 85304e1eee4c3886c39299099e8bcbf08d0cfe47
