### ISSUE TITLE
Problems with inserted semicolons in generated JS

### ISSUE THREAD

**Issue by tokland** [puffnfresh/roy#99]
This Roy code:

```
let f x =
  let a = 2
  a * x

console.log (f 4)
```

Generates this JS code:

```
var f = function(x) {
    console.log(1);
    var a = 2;;
    return a * x;
}
console.log((f(4)))
```

The double semicolons are just an aesthetic problem, but the lack of semicolons in single-line expressions can lead to syntactically incorrect JS.

**Comment by puffnfresh** [comment]
Pushed a change. The input now compiles to this:

```
var f = function(x) {
    var a = 2;
    return a * x;
};
console.log((f(4)));
```

**Comment by tokland** [comment]
swell, thanks.
